// @ts-nocheck
import React, { useEffect, useState } from 'react';
import { useSearchParams, useNavigate } from 'react-router-dom';
import { 
  StreamCall, 
  StreamTheme, 
  SpeakerLayout, 
  CallControls,
  useStreamVideoClient,
  CallingState,
  useCallStateHooks
} from '@stream-io/video-react-sdk';
import { useAuth } from '@/lib/authContext';
import { Loader2 } from 'lucide-react';

// --- SUB-COMPONENT: CALL UI ---
// This component sits inside StreamCall, so hooks are safe here
const CallUI = ({ onLeave }) => {
  const { useCallCallingState, useParticipantCount } = useCallStateHooks();
  const callingState = useCallCallingState();
  const participantCount = useParticipantCount();

  // Show loading while the WebRTC connection is actually being established
  if (callingState !== CallingState.JOINED) {
    return (
      <div className="min-h-screen flex flex-col items-center justify-center bg-slate-900 text-white">
        <Loader2 className="w-12 h-12 mb-4 animate-spin text-amber-500" />
        <p className="text-xl font-medium tracking-tight">Connecting to session...</p>
        <p className="text-slate-400 mt-2">Waiting for friend to join</p>
      </div>
    );
  }

  return (
    <StreamTheme>
      <div className="relative h-screen w-full bg-slate-950">
        <div className="absolute top-6 left-6 z-50 flex items-center gap-4">
           <div className="bg-slate-800/80 backdrop-blur px-4 py-2 rounded-full border border-slate-700 shadow-xl">
             <span className="text-amber-500 font-bold animate-pulse">● LIVE</span>
             <span className="ml-3 text-white font-medium">{participantCount} Participants</span>
           </div>
        </div>

        <SpeakerLayout participantsBarPosition='bottom' />
        
        <div className="absolute bottom-10 left-0 w-full flex justify-center z-50">
          <CallControls onLeave={onLeave} />
        </div>
      </div>
    </StreamTheme>
  );
};

// --- MAIN COMPONENT ---
export default function VideoCall() {
  const { user } = useAuth(); //
  const [searchParams] = useSearchParams();
  const navigate = useNavigate();
  const client = useStreamVideoClient(); //
  
  const [call, setCall] = useState(null);
  const [error, setError] = useState(null);
  
  const partnerId = searchParams.get('userId');

  useEffect(() => {
    // 🟢 THE FIX: Wait until client.user exists. 
    // If we call client.call() before the token handshake finishes, it crashes.
    if (!client || !client.user || !user?.id || !partnerId) {
      console.log("STREAM DEBUG - Waiting for client.user to initialize...");
      return;
    }

    // DETERMINISTIC ID: Same ID generated by both browsers
    const members = [user.id, partnerId].sort();
    const callId = `call_${members[0].split('-')[0]}_${members[1].split('-')[0]}`;
    
    console.log("STREAM DEBUG - Ready! Joining room ID:", callId);

    const myCall = client.call('default', callId);

    const initCall = async () => {
      try {
        await myCall.getOrCreate({
          data: {
            members: [
              { user_id: user.id, role: 'admin' },
              { user_id: partnerId, role: 'user' },
            ],
            ring: true, //
          },
        });
        await myCall.join();
        setCall(myCall);
      } catch (err) {
        console.error("Stream Call Error:", err);
        setError(err.message);
      }
    };

    initCall();

    return () => {
      myCall.leave();
    };
  }, [client, client?.user, user?.id, partnerId]); // Watch client.user state

  const handleLeave = () => {
    navigate('/FindFriends'); 
  };

  // ERROR HANDLING
  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-red-50 p-10">
        <div className="text-center text-red-600 bg-white p-8 rounded-3xl shadow-xl border border-red-100">
          <h2 className="text-2xl font-black mb-2">Connection Failed</h2>
          <p className="font-medium opacity-70 mb-4">{error}</p>
          <button 
             onClick={() => window.location.reload()} 
             className="px-6 py-3 bg-red-600 text-white rounded-xl font-bold hover:bg-red-700 transition-colors"
          >
            Try Again
          </button>
        </div>
      </div>
    );
  }

  // LOADING STATE
  if (!call) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-white">
        <div className="text-center">
          <Loader2 className="w-12 h-12 animate-spin mx-auto text-amber-500 mb-4" />
          <h2 className="text-3xl font-black text-slate-800 tracking-tight">Starting Call Engine</h2>
          <p className="text-slate-400 mt-2 font-medium">Authenticating with video servers...</p>
        </div>
      </div>
    );
  }

  return (
    <StreamCall call={call}>
      <CallUI onLeave={handleLeave} />
    </StreamCall>
  );
}